# Cloud Build configuration for PawConnect AI - Production
# Triggered on git push to main branch or manually
#
# Usage:
#   gcloud builds submit --config deployment/cloudbuild.yaml --substitutions=_REGION=us-central1
#
# Required substitutions:
#   _REGION: GCP region (default: us-central1)
#   _VPC_CONNECTOR: VPC connector name (optional, default: pawconnect-connector)
#   _REDIS_HOST: Redis host IP (optional, default: 10.0.0.3)
#
# IMPORTANT: Cloud Build Variable Escaping Rules
# ================================================
# Cloud Build interprets variables in YAML files. There are three types:
#
# 1. Built-in substitutions (no escaping needed):
#    $PROJECT_ID, $BUILD_ID, $COMMIT_SHA, $BRANCH_NAME, $TAG_NAME, etc.
#    Example: gcr.io/$PROJECT_ID/pawconnect-ai:$BUILD_ID
#    Note: $BUILD_ID is always available; $COMMIT_SHA/$SHORT_SHA only when triggered from git
#
# 2. User-defined substitutions (must start with _, no escaping needed):
#    $_REGION, $_VPC_CONNECTOR, $_REDIS_HOST (defined in substitutions section)
#    Example: --region=$_REGION
#
# 3. Bash shell variables (MUST use $$ to escape):
#    Any variable you define in bash scripts within the YAML
#    Example: SERVICE_URL=$$(gcloud run services describe ...)
#            echo "URL: $$SERVICE_URL"
#
# Common Error:
# If you get "invalid value for 'build.substitutions'" error, you forgot
# to escape a bash variable with $$. Change $variable to $$variable.

steps:
  # Step 1: Run tests
  - name: 'python:3.11.3'
    id: 'run-tests'
    entrypoint: 'bash'
    timeout: '900s'  # 15 minutes for tests
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov
        pytest tests/ --cov=pawconnect_ai --cov-report=xml --cov-report=term
    env:
      - 'TESTING_MODE=true'
      - 'MOCK_APIS=true'

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    timeout: '3600s'  # 60 minutes for building image
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - 'build'
      - '--progress=plain'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pawconnect-ai:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pawconnect-ai:latest'
      - '-f'
      - 'deployment/Dockerfile'
      - '.'
    waitFor: ['run-tests']

  # Step 3: Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    timeout: '600s'  # 10 minutes for pushing image
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/pawconnect-ai'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run with Production Configuration
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    timeout: '1200s'  # 20 minutes for deployment
    args:
      - 'run'
      - 'deploy'
      - 'pawconnect-main-agent'
      - '--image=gcr.io/$PROJECT_ID/pawconnect-ai:$BUILD_ID'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--vpc-connector=$_VPC_CONNECTOR'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=$_REGION,ENVIRONMENT=production,TESTING_MODE=False,MOCK_APIS=False,LOG_LEVEL=INFO,REDIS_HOST=$_REDIS_HOST,REDIS_PORT=6379,USE_GEMINI_FOR_CONVERSATION=True,GEMINI_MODEL_NAME=gemini-2.0-flash-001,VISION_API_ENABLED=True,PUBSUB_TOPIC_PREFIX=pawconnect-prod,FIRESTORE_COLLECTION_USERS=users,FIRESTORE_COLLECTION_APPLICATIONS=applications'
      - '--set-secrets=RESCUEGROUPS_API_KEY=rescuegroups-api-key:latest,REDIS_PASSWORD=redis-password:latest,DIALOGFLOW_AGENT_ID=dialogflow-agent-id:latest'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300s'
      - '--max-instances=20'
      - '--min-instances=1'
      - '--concurrency=80'
      - '--no-cpu-throttling'
      - '--cpu-boost'
      - '--service-account=$_SERVICE_ACCOUNT'
    waitFor: ['push-image']

  # Step 5: Run integration tests against deployed service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'integration-tests'
    entrypoint: 'bash'
    timeout: '600s'  # 10 minutes for integration tests
    args:
      - '-c'
      - |
        # Install Python dependencies
        apt-get update && apt-get install -y python3-pip
        pip3 install -r requirements.txt
        pip3 install pytest pytest-asyncio
        # Get service URL (using $$ to escape Cloud Build substitution)
        SERVICE_URL=$$(gcloud run services describe pawconnect-main-agent --region=$_REGION --format='value(status.url)')
        echo "Testing deployed service at: $$SERVICE_URL"
        # Run integration tests if they exist
        if [ -d "tests/integration" ]; then
          python3 -m pytest tests/integration/ --service-url=$$SERVICE_URL || echo "Integration tests failed or not available"
        else
          echo "No integration tests found, skipping"
        fi
    waitFor: ['deploy-cloud-run']

# Artifacts to save
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-artifacts/build-$BUILD_ID'
    paths:
      - 'coverage.xml'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

# Substitution variables
# User-provided substitutions (via --substitutions flag):
#   _REGION: GCP region for deployment
#
# Default values for optional substitutions:
substitutions:
  _REGION: 'us-central1'
  _VPC_CONNECTOR: 'pawconnect-connector'
  _REDIS_HOST: '10.0.0.3'  # Update with actual Memorystore IP after deployment
  _SERVICE_ACCOUNT: '${PROJECT_NUMBER}-compute@developer.gserviceaccount.com'

# Timeout for entire build (7200s = 2 hours)
timeout: '7200s'

# Tags for build
tags:
  - 'pawconnect'
  - 'production'
  - 'cloud-run'
