# Cloud Build configuration for PawConnect AI
# Triggered on git push to main branch

steps:
  # Step 1: Run tests
  - name: 'python:3.11.3'
    id: 'run-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov
        pytest tests/ --cov=pawconnect_ai --cov-report=xml --cov-report=term
    env:
      - 'TESTING_MODE=true'
      - 'MOCK_APIS=true'

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pawconnect-ai:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pawconnect-ai:latest'
      - '-f'
      - 'deployment/Dockerfile'
      - '.'
    waitFor: ['run-tests']

  # Step 3: Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/pawconnect-ai'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - 'pawconnect-main-agent'
      - '--image=gcr.io/$PROJECT_ID/pawconnect-ai:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,ENVIRONMENT=production'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=60s'
      - '--max-instances=10'
      - '--min-instances=1'
    waitFor: ['push-image']

  # Step 5: Run integration tests against deployed service
  - name: 'python:3.11.3'
    id: 'integration-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pip install pytest pytest-asyncio
        export SERVICE_URL=$(gcloud run services describe pawconnect-main-agent --region=$_REGION --format='value(status.url)')
        pytest tests/integration/ --service-url=$SERVICE_URL
    waitFor: ['deploy-cloud-run']

# Artifacts to save
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-artifacts/build-$BUILD_ID'
    paths:
      - 'coverage.xml'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

# Substitution variables
substitutions:
  _REGION: 'us-central1'

# Timeout for entire build
timeout: '1800s'

# Tags for build
tags:
  - 'pawconnect'
  - 'production'
  - 'cloud-run'
